In [90]:
import numpy as np
from scipy import linalg

In [91]:
print(dir(linalg))

['LinAlgError', 'LinAlgWarning', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_basic', '_batched_linalg', '_cythonized_array_utils', '_decomp', '_decomp_cholesky', '_decomp_cossin', '_decomp_interpolative', '_decomp_ldl', '_decomp_lu', '_decomp_lu_cython', '_decomp_polar', '_decomp_qr', '_decomp_qz', '_decomp_schur', '_decomp_svd', '_decomp_update', '_expm_frechet', '_fblas', '_flapack', '_linalg_pythran', '_matfuncs', '_matfuncs_expm', '_matfuncs_schur_sqrtm', '_misc', '_procrustes', '_sketches', '_solve_toeplitz', '_solvers', '_special_matrices', 'bandwidth', 'basic', 'blas', 'block_diag', 'cdf2rdf', 'cho_factor', 'cho_solve', 'cho_solve_banded', 'cholesky', 'cholesky_banded', 'circulant', 'clarkson_woodruff_transform', 'companion', 'convolution_matrix', 'coshm', 'cosm', 'cossin', 'cython_blas', 'cython_lapack', 'decomp', 'decomp_cholesky', 'decomp_lu', 'decomp_qr', 'decomp_schur', 'decomp_svd', 'det

In [92]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

d = linalg.det(array)

print(f'Determinant: {d}')

Determinant: 0.0


Array with the shape (3,2,2,2)

In [93]:
array = np.array([ [[[1 , 2], [3 , 4]],
                   [[5 , 6], [7 , 8]]],

                    [[[9 , 10], [11 , 12]],
                    [[13 , 14], [15 , 16]]],

                     [[[17 , 18], [19 , 20]],
                     [[21, 22],[23 , 24]]]

])

d = linalg.det(array)                # resulting shape is (3,2)

print(f'Determinant: {d}')

Determinant: [[-2. -2.]
 [-2. -2.]
 [-2. -2.]]


3X3 array

In [94]:
array = np.array([[1,2,3],
                  [4,5,5],
                  [7,8,9]])

d = linalg.det(array)                    # determinant
i = linalg.inv(array)                   # inverse
s = linalg.sqrtm(array)                # square root

# Trigometric function
sine = linalg.sinm(array)               
cosine = linalg.cosm(array)
print(f'{d:.2f} ===> Determinant\n\n{i} ===> Inverse\n\n{s} ===> Square Root\n\n{sine} ===> Sine\n\n{cosine} ===> Cosine')


-6.00 ===> Determinant

[[-0.83333333 -1.          0.83333333]
 [ 0.16666667  2.         -1.16666667]
 [ 0.5        -1.          0.5       ]] ===> Inverse

[[0.47884603+0.86956522j 0.38234703+0.17391304j 0.76651855-0.34782609j]
 [0.9439065 -0.2173913j  1.64332167-0.04347826j 1.06615216+0.08695652j]
 [1.66906833-0.43478261j 1.77752842-0.08695652j 2.44937246+0.17391304j]] ===> Square Root

[[-0.71660056 -0.25313339  0.37630753]
 [ 0.1957403   0.34314843 -0.20082912]
 [ 0.4100462  -0.04052376 -0.00111671]] ===> Sine

[[ 0.36106409 -0.35013927 -0.18340679]
 [-0.38289086  0.36880423 -0.68003268]
 [-0.63954096 -0.96109722 -0.25823101]] ===> Cosine


In [95]:
from scipy.special import sindg
A = np.array([[30 , 60],
      [90, 180]])

d = sindg(A)
print(d)
print(np.max(A))

[[ 0.5        0.8660254]
 [ 1.        -0.       ]]
180


In [96]:
a = np.array([[3,4]])
n = linalg.norm(a)

print(f'Norm: {n}')

Norm: 5.0


In [99]:
a = np.array([[7, 2, 3],
              [4 , 5 , 6],
              [6, 7 , 8]])
b = np.array([8 , 10 , 8])

x = linalg.solve(a,b,assume_a='sym')

print(x)

[ 1.2173913   8.60869565 -5.91304348]
